import fs from 'fs';
import path from 'path';
import archiver from 'archiver';
import { getSelectedAgents, getAnswers, getProject } from '../db/index.js';

// Agent templates - these would be loaded from the actual agent files
const AGENT_TEMPLATE = {
  'engineering-ai-engineer': {
    name: 'AI Engineer',
    role: 'Build machine learning models',
    files: ['agent.py', 'prompts.py', 'config.yaml']
  },
  'engineering-backend-architect': {
    name: 'Backend Architect',
    role: 'Design server systems',
    files: ['agent.py', 'prompts.py', 'config.yaml']
  },
  'marketing-content-creator': {
    name: 'Content Creator',
    role: 'Create marketing content',
    files: ['agent.py', 'prompts.py', 'config.yaml']
  },
  'design-ui-designer': {
    name: 'UI Designer',
    role: 'Design user interfaces',
    files: ['agent.py', 'prompts.py', 'config.yaml']
  }
  // ... more agents would be here
};

function generateAgentFiles(agentId, answers) {
  const template = AGENT_TEMPLATE[agentId] || {
    name: agentId,
    role: 'General purpose agent',
    files: ['agent.py', 'prompts.py', 'config.yaml']
  };
  
  const files = {};
  
  // Generate agent.py
  files['agent.py'] = `# ${template.name} Agent
"""
${template.role}
"""
from typing import Dict, Any

class ${template.name.replace(/[^a-zA-Z]/g, '')}Agent:
    def __init__(self, config: Dict[str, Any] = None):
        self.config = config or {}
        self.name = "${template.name}"
    
    async def run(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        # Your agent logic here
        return {"result": "completed", "agent": self.name}

# For direct execution
if __name__ == "__main__":
    agent = ${template.name.replace(/[^a-zA-Z]/g, '')}Agent()
    result = agent.run({"task": "example"})
    print(result)
`;
  
  // Generate prompts.py
  files['prompts.py'] = `# ${template.name} - Prompts

SYSTEM_PROMPT = """You are a ${template.name}.

${template.role}

Context:
- Business type: {business_type}
- Team size: {team_size}
- Goals: {goals}

Instructions:
- Be professional and efficient
- Follow best practices
- Prioritize quality
"""

USER_PROMPT_TEMPLATE = """Task: {task}

Please complete this task using your expertise.
"""
`;
  
  // Generate config.yaml
  files['config.yaml'] = `# ${template.name} Configuration
name: ${agentId}
description: ${template.role}

# Agent settings
settings:
  model: gpt-4
  temperature: 0.7
  max_tokens: 2000

# Capabilities
capabilities:
  - general_assistance
  
# Custom configuration
custom:
  business_type: {business_type}
`;
  
  return files;
}

export function generateProjectFiles(projectId) {
  const agents = getSelectedAgents(projectId);
  const answers = getAnswers(projectId);
  
  const answersMap = answers.reduce((acc, { question_key, answer_value }) => {
    acc[question_key] = answer_value;
    return acc;
  }, {});
  
  const files = {};
  
  // Generate main.py
  files['main.py'] = `"""
Agent Team - Main Orchestration
Generated by Agent Team Builder

Business Context:
${Object.entries(answersMap).map(([k, v]) => `- ${k}: ${v}`).join('\n')}
"""

from agents import *

class AgentTeam:
    def __init__(self):
        self.agents = {}
        ${agents.map(a => `self.agents["${a.agent_id}"] = ${a.agent_id.replace(/[^a-zA-Z]/g, '')}Agent()`).join('\n        ')}
    
    def run_all(self, task):
        results = {}
        for name, agent in self.agents.items():
            results[name] = agent.run(task)
        return results

if __name__ == "__main__":
    team = AgentTeam()
    print("Agent Team initialized!")
    print(f"Loaded {len(team.agents)} agents")
`;

  // Generate README.md
  files['README.md'] = `# Agent Team

Generated by Agent Team Builder

## Your Agent Team

${agents.map(a => `- **${a.agent_name}** (${a.agent_category}): ${a.is_recommended ? 'Recommended' : 'Selected'}`).join('\n')}

## Setup

\`\`\`bash
# Install dependencies
pip install -r requirements.txt

# Run the team
python main.py
\`\`\`

## Configuration

Edit \`config/agents.yaml\` to customize each agent.

## Business Context

${Object.entries(answersMap).map(([k, v]) => `- **${k}**: ${v}`).join('\n')}

---
*Generated on ${new Date().toISOString()}*
`;

  // Generate requirements.txt
  files['requirements.txt'] = `openai>=1.0.0
anthropic>=0.18.0
python-dotenv>=1.0.0
pyyaml>=6.0
`;

  // Generate CLAUDE.md (for AI collaboration)
  files['CLAUDE.md'] = `# Agent Team Context

You are working with a team of AI agents.

## Team Members

${agents.map(a => `### ${a.agent_name}
- ID: ${a.agent_id}
- Category: ${a.agent_category}
- Role: ${a.is_recommended ? 'Recommended for your business type' : 'Manually selected'}
`).join('\n')}

## Project Context

${Object.entries(answersMap).map(([k, v]) => `- **${k}**: ${v}`).join('\n')}

## Usage

Import and use individual agents:

\`\`\`python
from agents import content_creator

result = await content_creator.run({"task": "Write a blog post"})
\`\`\`
`;

  // Generate agents/__init__.py
  const agentImports = agents.map(a => 
    `from .${a.agent_id.replace(/-/g, '_')} import ${a.agent_id.replace(/[^a-zA-Z]/g, '')}Agent`
  ).join('\n');
  
  files['agents/__init__.py'] = `"""Agents Package"""
${agentImports}
`;

  // Generate each agent's files
  agents.forEach = Array.prototype.forEach;
  agents.forEach(agent => {
    const agentDir = `agents/${agent.agent_id.replace(/-/g, '_')}`;
    const agentFiles = generateAgentFiles(agent.agent_id, answersMap);
    
    Object.entries(agentFiles).forEach(([filename, content]) => {
      files[`${agentDir}/${filename}`] = content;
    });
  });

  // Generate AGENTS.md
  files['AGENTS.md'] = `# Agent Definitions

${agents.map(a => `## ${a.agent_name}

- **ID**: \`${a.agent_id}\`
- **Category**: ${a.agent_category}
- **Status**: ${a.is_recommended ? 'Recommended' : 'Selected'}
- **Required**: ${a.is_required ? 'Yes' : 'No'}

`).join('\n')}
`;

  return files;
}

export function createZipArchive(projectId) {
  return new Promise((resolve, reject) => {
    const files = generateProjectFiles(projectId);
    const archive = archiver('zip', { zlib: { level: 9 } });
    
    const chunks = [];
    archive.on('data', chunk => chunks.push(chunk));
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);
    
    Object.entries(files).forEach(([filename, content]) => {
      archive.append(content, { name: filename });
    });
    
    archive.finalize();
  });
}
