import archiver from 'archiver';
import { getSelectedAgents, getAnswers, getProject } from '../db/index.js';

// Agent templates
const AGENT_TEMPLATE = {
  'engineering-ai-engineer': {
    name: 'AI Engineer',
    role: 'Build machine learning models',
  },
  'engineering-backend-architect': {
    name: 'Backend Architect',
    role: 'Design server systems',
  },
  'marketing-content-creator': {
    name: 'Content Creator',
    role: 'Create marketing content',
  },
  'design-ui-designer': {
    name: 'UI Designer',
    role: 'Design user interfaces',
  }
};

function generateAgentFiles(agentId) {
  const template = AGENT_TEMPLATE[agentId] || {
    name: agentId,
    role: 'General purpose agent',
  };
  
  const className = template.name.replace(/[^a-zA-Z]/g, '');
  
  return {
    'agent.py': `# ${template.name} Agent
"""
${template.role}
"""
from typing import Dict, Any

class ${className}Agent:
    def __init__(self, config: Dict[str, Any] = None):
        self.config = config or {}
        self.name = "${template.name}"
    
    async def run(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        return {"result": "completed", "agent": self.name}

if __name__ == "__main__":
    agent = ${className}Agent()
    result = agent.run({"task": "example"})
    print(result)
`,
    'prompts.py': `# ${template.name} - Prompts
SYSTEM_PROMPT = """You are a ${template.name}.
${template.role}"""
USER_PROMPT_TEMPLATE = """Task: {task}"""
`,
    'config.yaml': `# ${template.name} Configuration
name: ${agentId}
settings:
  model: gpt-4
  temperature: 0.7
`
  };
}

export function generateProjectFiles(projectId, userApiKeys = {}) {
  const agents = getSelectedAgents(projectId);
  const answers = getAnswers(projectId);
  
  const answersMap = answers.reduce((acc, { question_key, answer_value }) => {
    acc[question_key] = answer_value;
    return acc;
  }, {});
  
  const files = {};
  
  // Generate .env.example with API keys (empty values for security)
  files['.env.example'] = `# =============================================================================
# Agent Team - Environment Variables Template
# =============================================================================
# Copy to .env and add your API keys
# NEVER commit .env to version control!
# =============================================================================

# OpenRouter.ai - 100+ AI Models (https://openrouter.ai)
OPENROUTER_API_KEY=

# Venice AI - Uncensored Models (https://venice.ai)
VENICE_API_KEY=

# Maton AI - Coding Assistant (https://maton.ai)
MASON_API_KEY=

# Skillboss.co - Business Agents (https://skillboss.co)
SKILLBOSS_API_KEY=

# OpenAI (optional)
OPENAI_API_KEY=

# Anthropic Claude (optional)
ANTHROPIC_API_KEY=

# Configuration
DEFAULT_PROVIDER=openrouter
DEFAULT_MODEL=gpt-4
`;
  
  // Generate main.py
  files['main.py'] = `"""Agent Team - Main Orchestration
Generated by Agent Team Builder

Business: ${answersMap.business_type || 'Custom'}
Team Size: ${answersMap.team_size || 'N/A'}
"""

class AgentTeam:
    def __init__(self):
        self.agents = {}
${agents.map(a => `        self.agents["${a.agent_id}"] = None  # ${a.agent_name}`).join('\n')}
    
    async def run_all(self, task):
        results = {}
        for name, agent in self.agents.items():
            if agent:
                results[name] = await agent.run(task)
        return results

if __name__ == "__main__":
    team = AgentTeam()
    print(f"Agent Team loaded with {len(team.agents)} agents")
`;

  // Generate README.md
  files['README.md'] = `# Agent Team

Generated by Agent Team Builder

## Your Agents
${agents.map(a => `- **${a.agent_name}** (${a.agent_category})`).join('\n')}

## Quick Start

1. Copy \`.env.example\` to \`.env\` and add your API keys
2. Run \`pip install -r requirements.txt\`
3. Run \`python main.py\`

## Integrations

This team supports multiple AI providers:
- **OpenRouter.ai** - 100+ models
- **Venice AI** - Uncensored
- **Maton AI** - Coding
- **Skillboss** - Business agents

## Configuration

Edit \`.env\` to configure your preferred provider and API keys.

---
Generated: ${new Date().toISOString()}
`;

  // Generate requirements.txt
  files['requirements.txt'] = `openai>=1.0.0
anthropic>=0.18.0
python-dotenv>=1.0.0
httpx>=0.25.0
pyyaml>=6.0
`;

  // Generate CLAUDE.md
  files['CLAUDE.md'] = `# Agent Team Context

## Team
${agents.map(a => `### ${a.agent_name}
- ID: ${a.agent_id}
- Category: ${a.agent_category}
`).join('\n')}

## Setup
1. Add API keys to .env
2. Run \`pip install -r requirements.txt\`
3. Edit agents as needed
`;

  // Generate agents/__init__.py
  files['agents/__init__.py'] = `"""Agents Package"""
# Import your agents here
`;

  // Generate each agent's files
  agents.forEach = Array.prototype.forEach;
  agents.forEach(agent => {
    const agentDir = `agents/${agent.agent_id.replace(/-/g, '_')}`;
    const agentFiles = generateAgentFiles(agent.agent_id);
    
    Object.entries(agentFiles).forEach(([filename, content]) => {
      files[`${agentDir}/${filename}`] = content;
    });
  });

  // Generate AGENTS.md
  files['AGENTS.md'] = `# Agent Definitions

${agents.map(a => `## ${a.agent_name}
- ID: \`${a.agent_id}\`
- Category: ${a.agent_category}
- Recommended: ${a.is_recommended ? 'Yes' : 'No'}
`).join('\n')}
`;

  return files;
}

export function createZipArchive(projectId, userApiKeys = {}) {
  return new Promise((resolve, reject) => {
    const files = generateProjectFiles(projectId, userApiKeys);
    const archive = archiver('zip', { zlib: { level: 9 } });
    
    const chunks = [];
    archive.on('data', chunk => chunks.push(chunk));
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('error', reject);
    
    Object.entries(files).forEach(([filename, content]) => {
      archive.append(content, { name: filename });
    });
    
    archive.finalize();
  });
}
